---
navbar:
  title: Slidify
  items: 
    - {item: Home, href: index, icon: home}
    - {item: "Start", href: start, icon: signin}
    - {item: Author, href: about, icon: pencil}
    - {item: Style, href: style, icon: hand-right, class: dropdown, 
        dropdown: true, menu: [
         {item: io2012, href: 'samples/intro'},
         {item: deck.js, href: 'samples/deck.js'},
         {item: shower, href: 'samples/shower'},
         {item: landslide, href: 'samples/landslide'}
        ]
      }
    - {item: Customize, href: customize, icon: gift}
    - {item: Extend, href: extend, icon: cogs}
    - {item: Publish, href: publish,  icon: github}
layout: landing
--- &hero

# Slidify

Stunning presentations from markdown

<a class="btn btn-primary btn-large" href='https://github.com/downloads/ramnathv/slidify/slidify_0.3.1.zip'>
 Windows Binary
</a>

*** video

<iframe width="500" height="360" src="http://www.youtube.com/embed/I95GOmLc7TA?rel=0&modestbranding=1" frameborder="0" allowfullscreen></iframe>

<!-- <iframe class="frame" width="500" height="375" 
  src="samples/dzslides/embedder.html#index.html">
  <a href="samples/dzslides/index.html">link to the presentation</a>
</iframe> -->

--- &div .features

*** first

###  <i class="icon-pencil icon-large"></i> Author

Write your slides in [RMarkdown](http://www.rstudio.com/ide/docs/r_markdown), a format that combines the core syntax of [Markdown](http://daringfireball.net/projects/markdown/) with embedded code chunks that are executed.

<p><a class="btn" href="http://www.rstudio.com/ide/docs/r_markdown">Learn More &raquo;</a></p>

*** second 

###  <i class="icon-hand-right icon-large"></i> Style

Turn your slides into a stunning HTML5 presentation using any of the more than ten slide generation frameworks supported.

<p><a class="btn" href="style.html">Learn More &raquo;</a></p>

*** third

###  <i class="icon-gift icon-large"></i> Customize

Add slide classes and css to customize your presentation. Use layouts to achieve more complex designs. 

<p><a class="btn" href="customize.html">Learn More &raquo;</a></p>

--- &div .features

*** first

### <i class='icon-cogs icon-large'></i> Extend

Add more functionality to your presentation using widgets. 
Slidify uses a modular design which encourages a plug and play infrastructure.

<p><a class="btn" href="extend.html">Learn More &raquo;</a></p>

*** second

### <i class='icon-github icon-large'></i> Publish

Share your presentation on [Github](http://github.com), [Dropbox](http://www.dropbox.com) or [Rpubs](http://www.rpubs.com) in minutes. Slidify has it all covered from creation to publication.

<p><a class="btn" href="publish.html">Learn More &raquo;</a></p>

*** third

### <i class='icon-check icon-large'></i> Get Started

Write a short slide deck and publish it to [Rpubs](http://www.rpubs.com) with a few clicks using [RStudio](http://www.rstudio.com), or to [Github](http://www.github.com) with a single line of code.

<p><a class="btn" href="start.html">Learn More &raquo;</a></p>

---

<a onmouseover="UE.Popin.preload();" href="#" onclick="UE.Popin.show(); return false;"></a>


